global:
  smtp_smarthost: "localhost:587"
  smtp_from: "alertmanager@netflux5g.local"
  smtp_auth_username: "alertmanager@netflux5g.local"
  smtp_auth_password: "password"

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "web.hook"
  routes:
    - match:
        severity: critical
      receiver: "critical-alerts"
    - match:
        severity: warning
      receiver: "warning-alerts"

receivers:
  - name: "web.hook"
    webhook_configs:
      - url: "http://localhost:5001/webhook"
        send_resolved: true

  - name: "critical-alerts"
    email_configs:
      - to: "admin@netflux5g.local"
        subject: "CRITICAL: {{ .GroupLabels.alertname }} - {{ .GroupLabels.service }}"
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Service: {{ .GroupLabels.service }}
          Severity: {{ .CommonLabels.severity }}

          {{ range .Alerts }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Started: {{ .StartsAt }}
          {{ end }}
        headers:
          Priority: "high"

  - name: "warning-alerts"
    email_configs:
      - to: "monitoring@netflux5g.local"
        subject: "WARNING: {{ .GroupLabels.alertname }} - {{ .GroupLabels.service }}"
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Service: {{ .GroupLabels.service }}
          Severity: {{ .CommonLabels.severity }}

          {{ range .Alerts }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Started: {{ .StartsAt }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "service"]