global:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 8s
  external_labels:
    cluster: 'netflux5g'
    monitor: 'netflux5g-prometheus'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - netflux5g-alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 15s

  # Node Exporter for system metrics
  - job_name: "node_exporter"
    static_configs:
      - targets: ["netflux5g-node-exporter:9100"]
    scrape_interval: 5s
    scrape_timeout: 3s

  # cAdvisor for container metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["netflux5g-cadvisor:8080"]
    scrape_interval: 5s
    scrape_timeout: 3s
    metrics_path: "/metrics"

  # Blackbox Exporter self-monitoring
  - job_name: "blackbox-exporter"
    static_configs:
      - targets: ["netflux5g-blackbox-exporter:9115"]
    scrape_interval: 30s

  # ICMP probes for 5G Core Network Functions
  - job_name: "icmp-5g-core"
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
          - mn.amf1    # Access and Mobility Management Function
          - mn.smf1    # Session Management Function
          - mn.upf1    # User Plane Function 1
          - mn.upf2    # User Plane Function 2
          - mn.nrf1    # Network Repository Function
          - mn.ausf1   # Authentication Server Function
          - mn.udm1    # Unified Data Management
          - mn.udr1    # Unified Data Repository
          - mn.pcf1    # Policy Control Function
          - mn.bsf1    # Binding Support Function
          - mn.nssf1   # Network Slice Selection Function
          - mn.scp1    # Service Communication Proxy
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: netflux5g-blackbox-exporter:9115
    scrape_interval: 10s
    scrape_timeout: 5s

  # ICMP probes for gNodeBs and UEs (optimized)
  - job_name: "icmp-ueransim"
    metrics_path: /probe
    params:
      module: [icmp_ue]